# Generated by Django 2.2.6 on 2020-05-08 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_auto_20200508_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of pet.', max_length=500, unique=True)),
                ('species', models.CharField(max_length=500, unique=True)),
                ('breed', models.CharField(max_length=500, unique=True)),
                ('weight_in_pounds', models.IntegerField(null=True)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this page. Generated by the system.', max_length=500)),
                ('special_instructions', models.TextField(help_text='Write special instructions for your animal.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this page was created. Automatically generated when the model saves.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this page was updated. Automatically generated when the model updates.')),
                ('Owner', models.ForeignKey(help_text='The owner of this pet.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
